name: release

on:
  push:
    tags: []

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v1

      - run: mkdir -p ./build

      - name: Check gen2, gen3 diff
        run: just test_self_compile

      - uses: actions/upload-artifact@v3
        with:
          name: quartz
          path: build/gen*.wat
