name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: []

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v1

      - run: mkdir -p ./build

      - name: Install Quartz
        run: just download $(just find_latest_version)

      - name: Build a compiler
        run: just build_compiler $(just find_latest_version) current

      - name: Run the test function
        run: |
          MODE=run-wat WAT_FILE=./build/quartz-current.wat cargo run --release -- compile --validate-address --test -o ./build/quartz-compiled.wat ./quartz/main.qz
          MODE=run-wat WAT_FILE=./build/quartz-compiled.wat cargo run --release

      - name: Run the integration tests
        run: cargo test --release -- --test-threads=1

      - name: Check if stable
        run: just build_compiler $(just find_latest_version) current && just check_if_stable --validate-address
