name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: []

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v1

      - run: mkdir -p ./build

      - name: Install Quartz
        run: just download $(just find_latest_version)

      - name: Build a compiler
        run: just build_compiler $(just find_latest_version) latest

      - name: Compile a test function
        run: MODE=run-wat WAT_FILE=./build/quartz-latest.wat cargo run --release -- compile --entrypoint test -o ./build/quartz-test.wat ./quartz/main.qz

      - name: Run the test function
        run: MODE=run-wat WAT_FILE=./build/quartz-test.wat cargo run --release

      - name: Check if stable
        run: just build_current_compiler && just check_if_stable
